package simple

import (
	"context"
	"embed"
	"fmt"

	engine "github.com/k8s-manifest-kit/engine/pkg"
	gotemplate "github.com/k8s-manifest-kit/renderer-gotemplate/pkg"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/lburgazzoli/k8s-controller-lib/pkg/builder"

	simpleApi "github.com/lburgazzoli/k8s-controller-lib/examples/simple-controller/api/v1alpha1"
	"github.com/lburgazzoli/k8s-controller-lib/pkg/reconciler"
	"github.com/lburgazzoli/k8s-controller-lib/pkg/reconciler/pipeline"
	"github.com/lburgazzoli/k8s-controller-lib/pkg/resources"
	"github.com/lburgazzoli/k8s-controller-lib/pkg/resources/gvks"
)

var (
	//go:embed templates/*.yaml.tmpl
	templates embed.FS
)

const (
	fieldManager   = "simple-controller"
	controllerName = "simpleApp"
)

func SetupWithManager(
	mgr ctrl.Manager,
) error {
	e, err := gotemplate.NewEngine(gotemplate.Source{
		FS:   templates,
		Path: "templates/*.yaml.tmpl",
	})
	if err != nil {
		return fmt.Errorf("failed to create templates renderer: %v", err)
	}

	// Create TypedPipeline with DeferredAutoWatch - controller and cache are
	// automatically injected by Builder.Complete() via ControllerAware and CacheAware interfaces
	p := pipeline.NewTyped[*simpleApi.SimpleApp](
		mgr.GetClient(),
		pipeline.WithFieldOwner(fieldManager),
		pipeline.WithActions(manifests(e)),
		pipeline.DeferredAutoWatch(),
	)

	// Create and complete the builder - TypedPipeline implements TypedReconciler
	b, err := builder.NewControllerBuilder[*simpleApi.SimpleApp](
		mgr,
		builder.WithName(controllerName),
	)
	if err != nil {
		return fmt.Errorf("unable to create builder: %w", err)
	}

	// Owns(gvks.Deployment) registers a static watch for Deployments.
	// Builder automatically informs the Pipeline about this via ExternalWatchesAware,
	// so the Pipeline's auto-watch will skip Deployments (avoiding redundant registration).
	// Other resources generated by actions will still be auto-watched dynamically.
	return b.
		For(&simpleApi.SimpleApp{}).
		Owns(gvks.Deployment).
		Complete(p)
}

// manifests returns an action that renders templates for SimpleApp resources.
func manifests(e *engine.Engine) reconciler.ActionFunc {
	return func(
		ctx context.Context,
		req *reconciler.Request,
		resp *reconciler.Response,
	) error {
		l := log.FromContext(ctx)
		l.Info("reconciling", "namespace", req.Object.GetNamespace(), "name", req.Object.GetName())

		u, err := resources.ToUnstructured(req.Client.Scheme(), req.Object)
		if err != nil {
			return err
		}

		objs, err := e.Render(
			ctx,
			engine.WithRenderTransformer(func(ctx context.Context, obj unstructured.Unstructured) (unstructured.Unstructured, error) {
				resources.SetLabel(&obj, "app.kubernetes.io/name", obj.GetName())
				return obj, nil
			}),
			engine.WithValues(u.Object),
		)
		if err != nil {
			return fmt.Errorf("failed to render manifests: %w", err)
		}

		for _, obj := range objs {
			resp.Objects(obj.DeepCopy())
		}

		return nil
	}
}
